### ISSUE TITLE
[REST Plugin] JSON does not accept NaN values

### ISSUE THREAD

**Issue by ulrich06** [kevoree-modeling/mwDB#4]
A **NaN** value in mwDB leads to a bad-formatted JSON:

```
{"world":0,"time":1464782931206,"id":274877907106,"name":"TEMP_444V","value":NaN,"type":"TEMPERATURE_INDOOR"}
```

![capture d ecran 2016-06-01 a 14 19 51](https://cloud.githubusercontent.com/assets/3204689/15709244/f787f3b0-2803-11e6-923d-410dc60ecfe3.png)

**Comment by dukeboard** [comment]
Now this is filtered, thanks for reporting !
